server:
  port: 8885

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunilsoni/spring-cloud-microservice-config
           
  application:
    name: MiService
    
      